### PR TITLE
Add support for Windows

### LINKED ISSUE #5: Crash on Windows: module 'pexpect' has no attribute 'spawn'
# Problem
On Windows I get the following error:

```
ecs-tunnel.exe -c XXXX -t YYYY -L 8000:8000
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Scripts\ecs-tunnel.exe\__main__.py", line 7, in <module>
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecs_tunnel\cli.py", line 100, in cli
    local_port_forward(ecs_tunnel=et, bind_config=lp)
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecs_tunnel\cli.py", line 34, in local_port_forward
    ecs_tunnel.local_port_tunnel(
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python311\Lib\site-packages\ecs_tunnel\_ecs_tunnel.py", line 174, in local_port_tunnel
    child = pexpect.spawn(command=self._resolved_aws_cli_exec, args=aws_cmd, env=self._get_env())
            ^^^^^^^^^^^^^
AttributeError: module 'pexpect' has no attribute 'spawn'
```

# Cause
`spawn` is not available on Windows (see https://github.com/pexpect/pexpect/issues/321#issuecomment-174547577 or the docs: https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows)

# Proposed solution
Use some different call to start the subprocess.

### PR DESCRIPTION
**Pull request by bencehornak**
Uses the `pexpect.popen_spawn.PopenSpawn` class instead of `pexpect.spawn()`, because the former is supported on Windows too ([reference](https://pexpect.readthedocs.io/en/stable/overview.html#pexpect-on-windows)).

Tested on Linux and Windows too.

Closes #5

### CODE REVIEW

**Comment by bencehornak** [comment]
@alastairmccormack did you have a chance to test my changes?

**Comment by alastairmccormack** [comment]
This is great! Sorry for the delay.

Tested on MacOS Ventura 13.6

**Comment by ghost** [comment]
@alastairmccormack please don't forget to publish a new release to pypi. Thank you so much!

**Comment by alastairmccormack** [comment]
Thanks again @bencehornak! It's now available from Pypi: https://pypi.org/project/ecs-tunnel/

**Pull request merged**
